### ISSUE TITLE
When updating a feature the page currently refreshes completely, need to swap to states instead so there's no refresh

### ISSUE THREAD

**Issue by park-d** [RBL1992/home#77]

**Comment by mbronstein1** [comment]
I noticed this and looked into it a bit. I'll take a closer look tomorrow as I complete the backend resolvers/typedefs consolidation

**Comment by park-d** [comment]
Don't worry about this one. I know what I have to do. Poornima just told me to do this as a quick fix because we were running out of time.

**Comment by park-d** [comment]
Unless you REALLY want to work on it, then feel free

**Comment by mbronstein1** [comment]
Sounds good. You can work on it. Let's just make sure we both don't touch it at the same time since I'm currently working on consolidating the code. Do you want to wait to update it to state-based until after I get it working with the backend? If that's too much re-writing over each others' work, we can hop on and work through the update functionality together.

**Comment by park-d** [comment]
I'm happy for you to work on it first, I'm going to be updating the code to have multiple houses as my first task, so take your time, and truly if you want to get into working on the state, feel free. My code for the featureList is really sloppy, so if you need to ask my any questions, just let me know.

**Comment by mbronstein1** [comment]
This is finished and PR is awaiting review. Once it is approved. I will close this issue.
